### ISSUE TITLE
Neptune 4 Pro - Black thumbnail

### ISSUE THREAD

**Issue by Benna08** [Molodos/ElegooNeptuneThumbnails-Prusa#12]
Hi there, thanks for your great work with this script.

I followed all the steps and all the thumbnail previews are appearing as a black image on my Neptune 4 Pro. Any idea what would be causing this? 

Thank you so much.

**Comment by Molodos** [comment]
Did you try using the "--printer=NEPTUNE4PRO" option to specify your printer manually? Also if you want to, you could send me one of the gcode files with the black thumbnails, maybe they could help me finding the error

**Comment by Benna08** [comment]
Thanks for your reply.

Yes, I did specify the printer manually. Just to clarify, the whole
thumbnail isn't black. It shows the bed in grey and then the object in
black. It does it with all the gcodes I've tried. Over 20.

**Comment by Benna08** [comment]
![Screenshot_20231128_095835_Gallery](https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa/assets/152066343/19c20b9e-9e44-45d4-9eb6-36c01cd0d6f7)

**Comment by Benna08** [comment]
Here you go. :)

**Comment by Molodos** [comment]
That looks like you have selected some black filament color in PrusaSlicer. I just know it from Cura: If you change the filament color in the slicer, it will also be like that in the thumbnail. Maybe you should look into that :)

**Comment by Benna08** [comment]
Ah, that makes sense. Thank you so much. I'll give it a try right now. :)

**Comment by Benna08** [comment]
Problem solved. Well, never really was a problem. Haha, I just had no Idea that the thumbnail preview actually represented the color of your filament also. Thanks for guiding me in the right direction and thanks again for this great script. :)
