### ISSUE TITLE
Bug when using multi-file display

### ISSUE THREAD

**Issue by MuellerMoritz** [Molodos/ElegooNeptuneThumbnails-Prusa#14]
Printer: Neptune 3 Pro
Slicer: Orca Slicer
Screen Firmware: V1.4.2

With the latest Screen Firmware multi-file display was released (enables the usage of folders on the SD-Card). Sadly the thumbnails aren't always displayed correctly, when using this feature.

- gcode in main directory -> works
- **gcode only in folder -> thumbnail is not displayed**
- gcode both in folder and main directory -> works with both copies

This might also be a bug in the screen firmware and not in this project, but i would be grateful if someone could check this.

**Comment by Molodos** [comment]
Thanks for the report. That's an issue with the screen firmware unfortunately. If it was the image encoding, then it would not work in all cases. Looking forward to Elegoo fixing that issue
