### ISSUE TITLE
The plugin crashes if your gcode contains Cyrylic

### ISSUE THREAD

**Issue by andronick83** [Molodos/ElegooNeptuneThumbnails-Prusa#2]
The plugin crashes with an error if your gcode contains Cyrylic: Example:

; bed_custom_texture = C:\\Users\\andro\\OneDrive\\Рабочий стол\\PrusaSlicerNeptune2PlatformTexture.svg

**Comment by Molodos** [comment]
Thanks for reporting that bug. It should be fixed in the latest release 1.1.4
