### ISSUE TITLE
iCCP Error

### ISSUE THREAD

**Issue by tekgecko** [Molodos/ElegooNeptuneThumbnails-Prusa#22]
Running this on a Neptune 4 pro.

Output is set as follows:

C:\Users\samma\Documents\_Git\ElegooNeptuneThumbnails-Prusa\dist\ElegooNeptuneThumbnails-Prusa.exe --printer="NEPTUNE4PRO";

Getting this error and no thumbnail seen by the firmware:

![u44DM4460i](https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa/assets/69898163/ba3129b7-b972-4656-bebc-75f30a08b122)

**Comment by Molodos** [comment]
The warnin should not cause any issues and can be ignored. However if the thumbnail isn't displayed, there must be another error.
If you share the generated gcode with me, I can have a look :)

**Comment by tekgecko** [comment]
Sure, thank you! It seems to generate some odd stuff at the top of the file

https://1drv.ms/u/s!Ak9kyhzCNFc-g4JjDGPc69cjsO29dQ?e=eNZFch

**Comment by tekgecko** [comment]
I tested further. Gcode from a network share doesn't display thumbnails on my Neptunes (I have several printers with a single mapped network share that hosts gcode). However, when I export the gcode to my desktop and transfer it directly to the printer using Fluidd, the thumbnails show up. This suggests the issue lies with how gcode is read from the network, not with your project.

**Comment by Molodos** [comment]
Thanks! Actually, the "odd stuff" at the top is the encoded image in the pretty odd format, the Neptune printers are using. It looks perfectly fine to me.
Also, I tried it on my Elegoo Neptune 4 Pro and it shows just fine:
![20240317_162937](https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa/assets/44006905/30fa2bc3-a8d4-4527-9145-d077940dfdb1)

**Comment by Molodos** [comment]
Okay, I see, that you found out the same thing, I guess that solves the issue :)

**Comment by tekgecko** [comment]
Yes! Seems to be with the way the firmware reads from the network, I will investigate further, thanks for your help!
