### ISSUE TITLE
Several layers color (M600)

### ISSUE THREAD

**Issue by mtmello2003** [Molodos/ElegooNeptuneThumbnails-Prusa#24]
When I slice several layers colors, using M600 to exchange filament between them, the script just consider the first layer color.
All others layers color are completely ignored.

**Comment by Molodos** [comment]
My script is based on the thumbnail generated by the slicer. I am just extending the image generated by the slicer, but I cannot cange the colors unfortunately. So this one does not have something to do with my script. If you think this is a bug, that needs to be reported, then please consider contacting the Slicer developers :)
