### ISSUE TITLE
Error when adding a filament change

### ISSUE THREAD

**Issue by schulahere** [Molodos/ElegooNeptuneThumbnails-Prusa#25]
When exporting a g-code file (calling the post processing script) that includes a filament change in orca the script terminates with an error and the file doesn´t get exported or transferred to the printer.
Everything works as expected when using the same file without the filament change command.

![image](https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa/assets/93193455/b5b122be-6ac7-45f7-9e5f-0cac76f5878f)

![image](https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa/assets/93193455/b79ed52b-ba17-4254-92da-0a20ec3953eb)

**Comment by Molodos** [comment]
Thanks for reporting and including all the details! I just published a fix :)

**Comment by schulahere** [comment]
thx, I´ll try it...
