### ISSUE TITLE
Neptune 4 Max

### ISSUE THREAD

**Issue by Kiroorik** [Molodos/ElegooNeptuneThumbnails-Prusa#8]
Please add the Neptune 4 Max profile

**Comment by Molodos** [comment]
I definitely plan adding support for those printers if I can somehow get access to them. I am currently already in contact with Elegoo regarding that :)

**Comment by Goodsmileduck** [comment]
let me know if you need help with testing or debugging, I have one Neptune 4 Max.
Also see people just using `--printer=NEPTUNE4PRO` seems working for them (found on reddit)
I will try it tomorrow

**Comment by Goodsmileduck** [comment]
It actually works, it's showing thumbnail on screen!

**Comment by Molodos** [comment]
Hi, sorry for the late reply. Ad [Goodsmileduck](https://github.com/Goodsmileduck) already said, you can try using --printer=NEPTUNE4PRO, which most likely works. It would be nice if someone could confirm that for me (I know, that Goodsmileduck also sent an image, but it seems a bit weird to be as the background is black and does not have the grid as seen in the Readme, so further confirmation would be nice)
After confirmation, I will officially add a Max and Plus option :)

**Comment by HautdogWater** [comment]
I can confirm this works for the Neptune 4 Plus as well.

**Comment by Molodos** [comment]
> I can confirm this works for the Neptune 4 Plus as well.

Thanks for that info, I will use it to officially support the N4Plus soon

**Comment by Molodos** [comment]
Good news: The Neptune 4 Plus and Max are now officially supported
